use std::env;
use std::fs;
use std::path::PathBuf;

mod base {
    include!("build.rs");

    pub fn run() {
        main();
    }
}

fn replace_once(text: String, old: &str, new: &str, label: &str) -> String {
    let count = text.matches(old).count();
    assert_eq!(count, 1, "{label}: expected one match, found {count}");
    text.replacen(old, new, 1)
}

fn main() {
    base::run();

    let out = PathBuf::from(env::var("OUT_DIR").unwrap());
    let generated = out.join("app_main_v0103.rs");
    let mut app = fs::read_to_string(&generated).expect("generated app source");

    let compatibility = r#"
trait ContextKeyboardCompat {
    fn wants_keyboard_input(&self) -> bool;
}

impl ContextKeyboardCompat for eframe::egui::Context {
    fn wants_keyboard_input(&self) -> bool {
        self.egui_wants_keyboard_input()
    }
}

"#;
    app = replace_once(
        app,
        "// @generated by build.rs from src/app_main.rs for Shade Editor 0.10.3.\n",
        &format!(
            "// @generated by build.rs from src/app_main.rs for Shade Editor 0.10.3.\n{compatibility}"
        ),
        "egui keyboard compatibility",
    );

    app = replace_once(
        app,
        "    fn ui_viewport(&mut self, ui: &mut egui::Ui) {\n        let Some(face)",
        "    fn ui_viewport(&mut self, ui: &mut egui::Ui) {\n        if workflow_v0103::ui_missing_viewport(self, ui) {\n            return;\n        }\n\n        let Some(face)",
        "missing Face viewport early hook",
    );
    app = replace_once(
        app,
        "\n        if workflow_v0103::ui_missing_viewport(self, ui) {\n            return;\n        }\n\n        let file_name = face",
        "\n        let file_name = face",
        "remove late missing Face viewport hook",
    );

    fs::write(&generated, app).expect("write compatibility-patched generated app source");
}
